#Docker Compose
version: "3.9"  
services:
  laravel:
    container_name: app-laravel
    image: 'usernameDockerHub/nam-project:latest'
    ports:
      - "80:8181"
    networks:
      - app-network  
networks:
  app-network:
    driver: bridge

