name: CI/CD - Pipeline
on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Autentication DockerHub
      - name: Check Repo
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      #Create variable
      - name: Create Variable
        run: echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV #variable with commit id

      #Build Dockerfile/DockerHub
      - name: Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/name-project:${{ env.GIT_SHA }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/name-project:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: exec script
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          first_ssh: |
            sh /caminho-scritp/script.sh

